# Website settings
baseurl: "/"
url: "http://faithworkcamps.com"

# Internal nav
nav:
  main:
    weblog: "/writing"
    photos: "/photos"
    devotions: "/devotions"
    files: "/files"
  writing:
    all: "/writing"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Faith Workcamps"
description: "Building faithful youth."
thumbnail_path: "fw-logo.png"
website_repo_url: "https://github.com/faithworkcamps/faithworkcamps.github.io"


# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/faithworkcamps"
    label: "Twitter"
    icon: "twitter-square"
    username: "@faithworkcamps"
  facebook:
    url: "https://www.facebook.com/groups/32770546126/"
    label: "Facebook"
    icon: "facebook-square"
  fpc:
    url: "https://github.com/faithworkcamps/faithworkcamps.github.io"
    label: "Faith"
    icon: "slideshare"
  github:
    url: "https://github.com/faithworkcamps/"
    label: "GitHub"
    icon: "github-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/New_York'
repository: faithworkcamps/faithworkcamps.github.io
future: true

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
